version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:4000

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
